my:
  name: rain
  age: 22


server:
  port: 8001
  servlet:
    context-path: /ssm

#thymeleaf
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  servlet:
    content-type: text/html
  mode: HTML5

spring:
  #profiles:
    #active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/huagong?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone = GMT%2B8&autoReconnect=true
    username: root
    password: 19960610
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true